### ISSUE TITLE
Disable sorting for certain column

### ISSUE THREAD

**Issue by clFaster** [BanForFun/react-select-table#6]
It would be great if the option to "sort" by the values in certain columns could be disabled (eg. phonebook, I might be intressted to sort by name but not by phone number). At the moment it only seems to be disabled by default for a column where the "path" property is not set.

**Comment by BanForFun** [comment]
Right, I might add an extra property for that in the future, but for the moment you can leave the 'path' property unset, and instead set the 'render' property to a callback which takes the entire row object as the second argument, and simply returns the desired property of the row (ex. `render: (n, row) => row.property`). Note that when the 'path' property is not set, you must set the 'key' property to a unique string that is not used as the path or key of any other column.
