### ISSUE TITLE
Is there OnBlur Feature available ??

### ISSUE THREAD

**Issue by samprasdsouza** [BanForFun/react-select-table#7]
Hello , I am using this react select table as input for array in a form . I need to perform certain onBlur actions. do we have this functionality . so can you suggest any other lib, thanks

**Comment by BanForFun** [comment]
Hello, no there is no such functionality built into the library, however, you could wrap the Table component in a div, and use its onBlur event like this: 
```jsx
<div onBlur={() => yourOnBlurActions()}>
  <Table {...yourProps} />
</div>
```
